name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libssl-dev \
            libffi-dev \
            libsqlite3-dev \
            libncurses5-dev \
            libncursesw5-dev \
            zlib1g-dev \
            libbz2-dev \
            libreadline-dev \
            liblzma-dev \
            python3-dev \
            python3-pip \
            unzip \
            git \
            curl \
            libjpeg-dev \
            libfreetype6-dev \
            libxml2-dev \
            libxslt1-dev \
            libyaml-dev \
            python3-venv \
            libgdbm-dev \
            libnss3-dev \
            libncurses5 \
            libncursesw5 \
            libffi-dev
          python3 -m pip install --upgrade pip
          pip install cython

      - name: Install Buildozer
        run: |
          pip install buildozer
          sudo apt-get install -y python3-pip
          sudo apt-get install -y libssl-dev

      - name: Build APK
        run: |
          buildozer android debug
