name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir buildozer cython
        sudo apt-get update
        sudo apt-get install -y \
          zip \
          unzip \
          openjdk-17-jdk \
          git \
          python3-pip \
          libffi-dev \
          libssl-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libbz2-dev \
          libreadline-dev \
          libsqlite3-dev \
          wget \
          curl \
          llvm \
          libncurses5 \
          libncursesw5 \
          zlib1g-dev

    - name: Pre-download Android NDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        cd ~/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25.2.9519653-linux.zip -O ndk.zip
        unzip -q ndk.zip

    - name: Build APK
      run: |
        buildozer android clean
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: bin/*.apk
