name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libreadline-dev \
            libgdbm-dev \
            libc6-dev \
            libbz2-dev \
            libexpat1-dev \
            build-essential \
            autoconf \
            automake \
            cmake \
            pkg-config \
            libtool \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libtiff-dev \
            libx11-dev \
            libxext-dev \
            libsm-dev \
            libxrender-dev

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install cython==0.29.33 buildozer==1.5.0

      - name: Create buildozer.spec if not exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            # Modify the spec file to use a specific NDK version
            sed -i 's/^android.ndk =.*/android.ndk = 25b/g' buildozer.spec
            sed -i 's/^android.ndk_path =.*/android.ndk_path = /home/runner/.buildozer/android/platform/android-ndk-r25b/g' buildozer.spec
          fi

      - name: Download Android NDK manually
        run: |
          mkdir -p /home/runner/.buildozer/android/platform
          cd /home/runner/.buildozer/android/platform
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          rm android-ndk-r25b-linux.zip

      - name: Build APK with increased timeout
        run: |
          export BUILDOZER_TIMEOUT=600
          buildozer android debug
          
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: bin/*.apk
