name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.10.8'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          libncurses5:i386 \
          libstdc++6:i386 \
          libgcc1:i386 \
          libgtk2.0-0:i386 \
          libpangox-1.0-0:i386 \
          libpangoxft-1.0-0:i386 \
          libidn11:i386 \
          python3-pip \
          python3-setuptools \
          python3-venv \
          zip \
          unzip \
          openjdk-17-jdk \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake
        
        python -m pip install --upgrade pip
        pip install buildozer==1.5.0 Cython==0.29.36 virtualenv
        
    - name: Install Android SDK tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform/
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip -q commandlinetools-linux-10406996_latest.zip -d $HOME/.buildozer/android/platform/
        mv $HOME/.buildozer/android/platform/cmdline-tools $HOME/.buildozer/android/platform/android-sdk
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        mv $HOME/.buildozer/android/platform/android-sdk/bin $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
        mv $HOME/.buildozer/android/platform/android-sdk/lib $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/
        
        export ANDROID_HOME=$HOME/.buildozer/android/platform/android-sdk
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
        
    - name: Build APK with Buildozer
      run: |
        # Ensure buildozer.spec exists
        if [ ! -f "buildozer.spec" ]; then
          echo "Error: buildozer.spec file not found in the repository root"
          exit 1
        fi
        
        # Build the APK
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: bin/*.apk
        if-no-files-found: error
