name: Build APK App - Docker Method
on: workflow_dispatch

jobs:
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Update buildozer.spec
        run: |
          if [ -f buildozer.spec ]; then
            # Update or add the NDK version
            if grep -q "^android.ndk =" buildozer.spec; then
              sed -i 's/^android.ndk =.*/android.ndk = 25b/g' buildozer.spec
            else
              echo "android.ndk = 25b" >> buildozer.spec
            fi
            
            # Fix duplicate requirements if they exist
            if [ $(grep -c "^requirements =" buildozer.spec) -gt 1 ]; then
              reqs=$(grep "^requirements =" buildozer.spec | sed 's/^requirements = //g' | tr '\n' ',')
              reqs=${reqs%,}
              sed -i '/^requirements =/d' buildozer.spec
              echo "requirements = $reqs" >> buildozer.spec
            fi
            
            echo "Updated buildozer.spec:"
            cat buildozer.spec
          else
            echo "buildozer.spec not found!"
            exit 1
          fi

      - name: Build APK with Docker
        run: |
          # Create a volume for buildozer cache to speed up future builds
          docker volume create buildozer-cache
          
          # Run the build in a Kivy buildozer container
          docker run --rm \
            -v "$PWD":/home/user/hostcwd \
            -v buildozer-cache:/home/user/.buildozer \
            -w /home/user/hostcwd \
            --env BUILDOZER_VERBOSE=1 \
            kivy/buildozer:latest \
            buildozer android debug
          
          # Check if the build was successful
          if [ -d "bin" ] && [ "$(ls -A bin/*.apk 2>/dev/null)" ]; then
            echo "Build successful! APK created."
          else
            echo "Build failed or no APK generated."
            exit 1
          fi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-package
          path: bin/*.apk
          if-no-files-found: warn
