name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            libncurses5 \
            libstdc++6 \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncursesw5 \
            libreadline6-dev \
            libgdbm-dev \
            libc6-dev \
            libbz2-dev \
            libexpat1-dev \
            build-essential \
            autoconf \
            automake \
            cmake \
            pkg-config \
            libtool \
            libltdl-dev \
            libjpeg-dev \
            libfreetype6-dev \
            libpng-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libtiff-dev \
            libx11-6 \
            libx11-dev \
            x11proto-core-dev \
            libxext-dev \
            libsm-dev \
            libxrender-dev

          pip install --upgrade pip
          pip install cython buildozer

      - name: Build APK
        run: |
          buildozer android debug
