name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel
        pip install --upgrade pip
        pip install --user buildozer

    - name: Add local bin to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer android debug
